name: benlew.is
db:
  main_db:
    prod:
      migration: "postgresql://postgres:***@localhost:5432/me?sslmode=disable"
      read: "postgresql://postgres:***@localhost:5432/me?sslmode=disable"
      write: "postgresql://postgres:***@localhost:5432/me?sslmode=disable"
    test:
      migration: "postgresql://postgres:***@localhost:5432/me_test?sslmode=disable"
      read: "postgresql://postgres:***@localhost:5432/me_test?sslmode=disable"
      write: "postgresql://postgres:***@localhost:5432/me_test?sslmode=disable"
