name: benlew.is
db:
  main_db:
    prod:
      drivername: postgres
      host: localhost
      port: 5432
      username: postgres
      password: ''
      database: me
    test:
      drivername: postgres
      host: localhost
      port: 5432
      username: postgres
      password: ''
      database: me_test
